# Intro to Numpy

![](https://www.freecodecamp.org/espanol/news/content/images/2021/04/numpy-1-1-.png)

### ¿Qué es numpy?

Numpy es una biblioteca en Python que **permite realizar operaciones matemáticas avanzadas de forma eficiente** con estructuras de datos de alto rendimiento, principalmente **arrays**.

### ¿Por qué usar numpy?

Usar numpy sobre las listas de Python tiene una serie de ventajas como la **rapidez y la eficiencia** en operaciones matemáticas y de matriz. Además, numpy es una biblioteca muy popular y ampliamente utilizada en el campo de la **ciencia de datos** y el aprendizaje automático. **Es la base** de muchas otras bibliotecas de Python como **pandas, scikit-learn**...

### ¿Cómo instalar numpy?

Para instalar numpy, simplemente ejecuta el siguiente comando en tu terminal:

```bash
pip install numpy
```

## Conceptos Básicos de Numpy

A continuación, vamos a ver algunos conceptos básicos de numpy, primero debemos importar la librería:

In [3]:
# import numpy

import numpy as np

### Crear un array

Numpy gira en torno a un objeto llamado **`array`** que es una **matriz multidimensional de elementos del mismo tipo**. 

💡 Para crear un array, puedes usar la función **`np.array()`** y pasar una lista de elementos como argumento.

In [9]:
my_list = [1,2,4,5]
np.array(my_list)

array([1, 2, 4, 5])

💡 También podemos crear arrays de ceros (`np.zeros()`), de unos (`np.ones()`), y con valores constantes específicos utilizando `np.full()`. 

In [15]:
np.zeros(3)
np.ones(7)
np.full(4,7)

array([7, 7, 7, 7])

💡 Podemos crear secuencias de números consecutivos usando `np.arange()` o `np.linspace()`. También podemos crear arrays de números aleatorios usando `np.random.rand()`.

In [23]:
np.arange(1,6,0.5)


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [21]:
np.random.rand(4,6)

array([[0.25768657, 0.11110362, 0.37748425, 0.64288864, 0.06936094,
        0.63042261],
       [0.09997846, 0.7736784 , 0.90052233, 0.74634597, 0.97637271,
        0.62989228],
       [0.05146154, 0.97896223, 0.00300188, 0.09488991, 0.74676839,
        0.25906632],
       [0.72828327, 0.94776203, 0.14885792, 0.05039687, 0.09567393,
        0.11724752]])

In [24]:
np.random.randint(0,40,14)

array([30, 20, 24, 34, 14, 19, 22, 24, 12, 17, 17, 26, 10, 13])

In [26]:
np.random.rand(4,3)

array([[0.59571232, 0.4078009 , 0.425098  ],
       [0.18895636, 0.38753726, 0.51028386],
       [0.85057424, 0.92761022, 0.99143557],
       [0.62212008, 0.27735298, 0.54456988]])

In [2]:
np.linspace(0,7,5)

NameError: name 'np' is not defined

In [3]:
np.array([127,137,147]) +2

array([129, 139, 149])

In [6]:
my_array = np.array([127,137,147])

### El tipo de datos de un array

Recuerda que los arrays de numpy tienen un **tipo de datos** asociado. Puedes especificar el tipo de datos al crear un array o numpy intentará inferirlo automáticamente. Es muy importante tener en cuenta el tipo de datos de un array, ya que puede afectar a la precisión de los cálculos y al uso de la memoria. Los tipos principales son:

- **`int`**: Número entero
  - **`int8`**: Entero de 8 bits: -128 a 127
  - **`int16`**: Entero de 16 bits: -2^15 a 2^15-1
  - **`int32`**: Entero de 32 bits: -2^31 a 2^31-1
  - **`int64`**: Entero de 64 bits: -2^63 a 2^63-1
- **`float`**: Número con decimales (coma flotante)
  - **`float16`**: Número de coma flotante de 16 bits
  - **`float32`**: Número de coma flotante de 32 bits
  - **`float64`**: Número de coma flotante de 64 bits 
- **`bool`**: Booleano
- **`string`**: Cadena de texto
- **`object`**: Objeto de Python

Dentro de los `int` y `float`, también puedes especificar si quieres que sean **signed** o **unsigned**. Por ejemplo, `uint8` es un entero sin signo de 8 bits. Es decir, alberga valores de 0 a 255 (2^8-1). Un caso clásico de un array de tipo `uint8` es una imagen en escala de grises, donde cada píxel tiene un valor entre 0 y 255. El 0 representa el color negro y el 255 el blanco.

💡 En numpy podemos ver el tipo de un array usando el método `.dtype`

In [7]:
my_array.dtype

dtype('int64')

💡 También podemos cambiar el tipo de un array usando el método `.astype()`

In [9]:
my_array.astype(bool)

array([ True,  True,  True])

### La Forma de un Array (a.k.a. Shape)

La "forma" de un array en numpy es un concepto fundamental que **describe las dimensiones del array**. Se refiere al **número de elementos en cada dimensión** y se representa por una tupla de enteros. Cada número en esta tupla indica el tamaño del array en esa dimensión. Por ejemplo, un array de una dimensión (un vector) con 4 elementos tendría una forma de (4,), mientras que un array de dos dimensiones (una matriz) con 3 filas y 5 columnas tendría una forma de (3, 5).

![](https://pbs.twimg.com/media/FD1qSBqVgAg7078.jpg:large)

* Un **vector**, que es un array de una sola dimensión, podría tener una forma (n,) donde n es el número de elementos en el vector.
* Una **matriz**, que es un array de dos dimensiones, podría tener una forma (m, n) donde m es el número de filas y n el número de columnas.
* Un **tensor**, que es un array de tres dimensiones, a menudo utilizado en ciencias de datos para representar conjuntos de imágenes o datos espaciotemporales, podría tener una forma (p, m, n) donde p representa un conjunto de matrices de dimensiones m x n.

💡 La propiedad `.shape` de un objeto numpy array se puede utilizar para obtener la forma actual del array:

In [10]:
my_array.shape

(3,)

💡 Es posible modificar la forma de un array usando el método `.reshape()`.

In [13]:
my_matrix = np.arange(6)
my_matrix.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

💡 También podemos "aplanar" un array (convertirlo a un vector) usando `.flatten()`

In [14]:
my_matrix.flatten()

array([0, 1, 2, 3, 4, 5])

## Operaciones Básicas

Podemos **sumar, restar, multiplicar y dividir** arrays de numpy de la misma forma que lo haríamos con números. ⚠️ Es importante tener en cuenta que estas operaciones se realizan **elemento a elemento**, por lo que **ambos arrays deben tener la misma forma.**

In [17]:
my_array * 37

array([4699, 5069, 5439])

💡 También podemos aplicar funciones matemáticas a un array de numpy, como **`np.sin()`, `np.cos()`, `np.exp()`, `np.log()`**...

In [19]:
np.sin(my_array)
np.cos(my_array)

array([ 0.2323591 ,  0.33416538, -0.79313642])

## Agregación y Estadísticas

Numpy proporciona una serie de funciones para realizar **operaciones de agregación y estadísticas** en arrays. Algunas de las más comunes son:

- **`np.sum()`**: Suma de todos los elementos del array
- **`np.mean()`**: Media de los elementos del array
- **`np.median()`**: Mediana de los elementos del array
- **`np.min()`**: Valor mínimo del array
- **`np.max()`**: Valor máximo del array
- **`np.argmin()`**: Índice del valor mínimo del array
- **`np.argmax()`**: Índice del valor máximo del array

In [24]:
np.sum(my_array)
np.mean(my_array)
np.std(my_array)
my_array[::-1]

array([147, 137, 127])

💡 También podemos calcular la posición del elemento máximo usando **`np.argmax()`** o **`np.argmin()`**

In [26]:
np.argmax(my_array)
np.argmin(my_array)

np.int64(0)

## Array Slicing

Al igual que en las listas de Python, podemos **acceder a elementos individuales o a subconjuntos de elementos** en un array de numpy utilizando la técnica de **slicing**. Para ello, podemos utilizar la notación de corchetes y dos puntos `:`.

In [30]:
my_array[0:1]

array([127])

## Array Masking

El **enmascaramiento de arrays** es una técnica que nos permite **filtrar** los elementos de un array basándonos en una **condición lógica**. Por ejemplo, podemos seleccionar todos los elementos de un array que sean mayores que un cierto valor, o que cumplan una determinada condición. Esto será especialmente útil cuando trabajemos con tablas de datos y queramos filtrar filas o columnas basándonos en ciertas condiciones.

In [4]:
my_vector = np.array([0,1,2,3,4])
my_mask = np.array([False, True, False, True, False])
my_vector[my_mask]

array([1, 3])

In [7]:
my_ages = np.array([12, 23, 34, 45, 6])
ages_over_18_mask = my_ages > 25
my_ages [ages_over_18_mask]
np.mean(my_ages[ages_over_18_mask])

np.float64(39.5)

## 💪 Ejercicios

A continuación, te propongo algunos ejercicios para que practiques tus habilidades con numpy

### Ejercicio I: The Alien Invasion

El ejercicio original puede encontrarse [aquí](https://matesanz.github.io/python-machine-learning-course/%F0%9F%A7%AA-Exercises/the-alien-invasion/).

In [8]:
import numpy as np


fleet_data = np.array([
    [120, 40, 25, 2.5, 10],
    [85, 60, 30, 5.0, 5],
    [100, 50, 35, 4.5, 7],
    [120, 40, 25, 2.5, 9],
    [150, 50, 30, 3.0, 10],
], dtype=np.float32)

CARACTERISIICAS DE LA PRIMERA NAVE. 1FILA 

In [9]:
fleet_data[0]

array([120. ,  40. ,  25. ,   2.5,  10. ], dtype=float32)

DAME LAS VELOCIDADES  DE TODAS LAS NAVES 

In [18]:
fleet_data[:,3] 

array([2.5, 5. , 4.5, 2.5, 3. ], dtype=float32)

velocidad media de las naves 

In [19]:
speed = fleet_data[:,3]
speed.mean()

np.float32(3.5)

velocidad maxima

In [20]:
speed.max()

np.float32(5.0)

velocidad minima

In [21]:
speed.min()

np.float32(2.5)

posicion nave de mayor velocidad

In [24]:
speed.argmax()

np.int64(1)

posicion nave mas lenta

In [25]:
speed.argmin()

np.int64(0)

In [26]:
fleet_data

array([[120. ,  40. ,  25. ,   2.5,  10. ],
       [ 85. ,  60. ,  30. ,   5. ,   5. ],
       [100. ,  50. ,  35. ,   4.5,   7. ],
       [120. ,  40. ,  25. ,   2.5,   9. ],
       [150. ,  50. ,  30. ,   3. ,  10. ]], dtype=float32)

In [28]:
power = fleet_data[:,4]
power

array([10.,  5.,  7.,  9., 10.], dtype=float32)

maxima potencia de naves

In [29]:
power.max()

np.float32(10.0)

minima potencia 

In [30]:
power.min()

np.float32(5.0)

VOLUMEN DEL ARRAY

In [33]:
fleet_height = fleet_data[:,0]
fleet_width = fleet_data[:,1]
fleet_length = fleet_data[:,2]
fleet_height, fleet_width, fleet_length

(array([120.,  85., 100., 120., 150.], dtype=float32),
 array([40., 60., 50., 40., 50.], dtype=float32),
 array([25., 30., 35., 25., 30.], dtype=float32))

In [34]:
volumen_naves = fleet_height * fleet_width * fleet_length
volumen_naves

array([120000., 153000., 175000., 120000., 225000.], dtype=float32)

### Ejercicio II: manipulando imágenes

Dada una imagen a color representada por un array de numpy de forma `(m, n, c)` donde `m` es el número de filas y `n` el número de columnas y `p` las bandas de color (RGB), escribe una función que reciba la imagen y devuelva una nueva imagen que contenga solo la mitad derecha de la imagen original. para convertir la imagen en un array de numpy, puedes usar la función `PIL.Image.open()` del módulo `PIL` y luego convertir la imagen en un array de numpy usando `np.asarray()`.

In [19]:
from PIL import Image
import requests

IMAGE_URL = "https://estaticos-cdn.prensaiberica.es/clip/6040f332-9afa-471d-b076-c060ae37450a_alta-libre-aspect-ratio_default_0.jpg"

response = requests.get(IMAGE_URL, stream=True)
image_pil = Image.open(response.raw)
image_array = np.array(image_pil)
Image.fromarray(image_array)  # show the image

ModuleNotFoundError: No module named 'PIL'

### Ejercicio III: Crea un Tres en Raya

To try out your new skills, try to create a TicTacToe game using Numpy arrays. Fill the functions below to create a game that can be played by two players.